### ISSUE TITLE
camera is not detected even when connected 

### ISSUE THREAD

**Issue by Bhumikasingh0110** [dilawar/MouseBehaviour#2]
camera is not detected even when it is connected with a error i found before also.

![screenshot from 2017-07-11 10-47-57](https://user-images.githubusercontent.com/28945960/28052179-f05fc4c0-6626-11e7-9f1a-416e4ee39cc1.png)
and I got the USB port with 4  wires coming out .If you want anything else made from the electronics workshop , please let me know.

**Comment by dilawar** [comment]
Try 

     $ sudo rm -f /tmp/eye_blink_socket 

and try gain.

**Comment by Bhumikasingh0110** [comment]
still not working...i can see the camera green light glowing but it doesnt detect the camera.

**Comment by dilawar** [comment]
This was fixed after adding user to `pgrimaging` group and updating udev rules. One needs to run the script https://github.com/dilawar/MouseBehaviour/blob/master/PointGreyCamera/external/spin-conf
