### ISSUE TITLE
error occured while analysing data

### ISSUE THREAD

**Issue by Bhumikasingh0110** [dilawar/MouseBehaviour#4]
![error1](https://user-images.githubusercontent.com/28945960/28403381-12bc5d5e-6d42-11e7-94f4-eca292b2cbcd.png)

**Comment by Bhumikasingh0110** [comment]
in another laptop libtiff module is not there.
![error2](https://user-images.githubusercontent.com/28945960/28404427-dea1847c-6d46-11e7-9822-6fd401b8c140.png)

**Comment by dilawar** [comment]
Second issue you can solve by installing 

     $ sudo apt install python-libtiff 

The first issue has problem in formatting of datacolumn in one of the line . Can you upload the dat file on which it failed?

**Comment by Bhumikasingh0110** [comment]
![error3](https://user-images.githubusercontent.com/28945960/28409834-731f15d0-6d59-11e7-854b-8e2c2a465d75.png)
still error is there

**Comment by Bhumikasingh0110** [comment]
the dat file
​
 trial_010.tif
<https://drive.google.com/file/d/0B7WPkTv6HfJNME5nM2NlUVRSUGs/view?usp=drive_web>
​


[image: photo]
*Bhumika Singh Rathore*
Third Year Undergraduate
Department of Biotechnology
IIT Kharagpur
7548095861 | bhumikasinghrathore@gmail.com

**Comment by dilawar** [comment]
This is a known bug in libtiff. Following will fix it.

    $ pip install libtiff --user 

Or, 

     $ sudo chown -R a+w /usr/lib/python2.7/dist-packages/libtiff/tiff_h*.py 

Any of the above would fix it. Check the path in `sudo chown` command.

**Comment by Bhumikasingh0110** [comment]
thanks

**Comment by dilawar** [comment]
The formatting error is still there?

**Comment by Bhumikasingh0110** [comment]
I mailed you the dat file of the trial . It was not working till yesterday evening.

**Comment by dilawar** [comment]
Fixed now. Don't close the issue unless fixed. 

When a timestamp is improper, it is ignored.

**Comment by Bhumikasingh0110** [comment]
![error4](https://user-images.githubusercontent.com/28945960/28453608-a900b494-6e15-11e7-9aba-4b022bc65159.png)
all the trial got the plot but summary map is not there

**Comment by dilawar** [comment]
Latest commit 4303f71might fix it. If not, create directory `_analysis` in
the same folder where you data is kept and rerun the script.
