### ISSUE TITLE
to get the learning curve

### ISSUE THREAD

**Issue by Bhumikasingh0110** [dilawar/MouseBehaviour#6]
to get the learning curve:
adding plot values of all the trials and taking the average. two different to be made; one for the probe trial and one for the US+ trials.

**Comment by dilawar** [comment]
Each session has 80 trials. Now

- Compute a Boolean True/False representing if mouse has learnt? Which algorithm you want to use.
- For each session (i.e. 80 trials), plot these true/false?

**Comment by Bhumikasingh0110** [comment]
so we get a plot of the blink value in each trial like this
![558_l_1](https://user-images.githubusercontent.com/28945960/28555528-28f24aae-711e-11e7-9b04-f11fddefb2d4.png)
all the blink values from all the trials except the probe trials should be averaged(add all the values at a given point of time and divide it by no. of trials used to get the values) and that gives a new plot of average blink values in one session wrt time. similarly, it has to be done for the probe trials in the session.
both the plots(for US and probe ) should be present in the same graph that will explain the learning.

**Comment by dilawar** [comment]
Averaging is not a good idea. I'll do the averaging along with raw data.

**Comment by dilawar** [comment]
![image](https://user-images.githubusercontent.com/895681/28569864-46133aea-7159-11e7-9e73-635cc3d589fc.png)

Command is same as before 

    $ python analyze_trial.py /path/to/folder

and check the summary.png file.
